<a href="https://colab.research.google.com/github/ArchanGhosh/Regression-Practice-Examples/blob/master/BGD_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import numpy as np
import tensorflow as tf

In [0]:
class BGDRegression(object):
  def __init__(self, eta=0.1, n_iter=1000):
    self.eta=eta
    self.n_iter=n_iter
  def fit(self, X, y):
    m,n=X.shape
    ones=tf.ones(shape=[m,1], dtype=tf.dtypes.float64)
    X= tf.concat([ones, X], axis=1)

    self.theta = tf.Variable(tf.random.normal(shape=[n+1, 1], dtype=tf.dtypes.float64))
    for i in range(self.n_iter):
      gradients = 2 / m * tf.transpose(X) @ (X @ self.theta - y)
      self.theta.assign(self.theta - self.eta * gradients)
    return self
  def predict(self,X):
    m,n=X.shape
    ones=tf.ones(shape=[m,1], dtype=tf.dtypes.float64)
    X = tf.concat([ones, X], axis=1)
    return X @ self.theta 


In [0]:
from tensorflow.keras.datasets import boston_housing

In [0]:
(X_train, y_train), (X_test, y_test) = boston_housing.load_data()

In [0]:
X_train.shape

(404, 13)

In [0]:
y_train.shape

(404,)

In [0]:
X_test.shape

(102, 13)

In [0]:
y_train = y_train.reshape(-1, 1)

In [0]:
y_test = y_test.reshape(-1, 1)

In [0]:
mean = tf.reduce_mean(X_train, axis= 1, keepdims=True)

In [0]:
std = tf.math.reduce_std(X_train, axis=1 , keepdims=True)

In [0]:
X_scaled = (X_train - mean) / std

In [0]:
bgd_reg = BGDRegression()

In [0]:
X_train = tf.Variable(X_scaled) 

In [0]:
y_train = tf.Variable(y_train)

In [0]:
bgd_reg.fit(X_train, y_train)

In [0]:
bgd_reg.theta

<tf.Variable 'Variable:0' shape=(14, 1) dtype=float64, numpy=
array([[-3.23211698e+198],
       [ 1.55453724e+198],
       [ 1.31047216e+198],
       [ 1.37380357e+198],
       [ 1.61589911e+198],
       [ 1.60447047e+198],
       [ 1.46648983e+198],
       [ 2.99965866e+196],
       [ 1.52266141e+198],
       [ 1.43091783e+198],
       [-7.30249116e+198],
       [ 1.17988947e+198],
       [-7.11676444e+198],
       [ 1.33011792e+198]])>

In [0]:
bgd_reg.predict(X_train)

<tf.Tensor: shape=(404, 1), dtype=float64, numpy=
array([[-4.29510578e+199],
       [-4.26945518e+199],
       [-4.18201833e+199],
       [-4.15119574e+199],
       [-4.20399229e+199],
       [-4.28277648e+199],
       [-4.21005517e+199],
       [-4.34238942e+199],
       [-3.97823614e+199],
       [-4.33886982e+199],
       [-4.18184921e+199],
       [-3.14138215e+199],
       [-4.28385084e+199],
       [-4.14388211e+199],
       [-4.07062868e+199],
       [-3.05305374e+199],
       [-4.20453913e+199],
       [-4.29855779e+199],
       [-4.28656179e+199],
       [-4.34821993e+199],
       [-3.09744632e+199],
       [-4.15911542e+199],
       [-4.27071031e+199],
       [-4.29081221e+199],
       [-4.15801367e+199],
       [-4.21020876e+199],
       [-4.30977251e+199],
       [-4.20435795e+199],
       [-4.31028387e+199],
       [-4.34989900e+199],
       [-4.26741418e+199],
       [-4.19531283e+199],
       [-3.98811043e+199],
       [-4.30239190e+199],
       [-4.15373980e+199],
     