<a href="https://colab.research.google.com/github/ArchanGhosh/Regression-Practice-Examples/blob/master/Logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf
import numpy as np

In [0]:
class LogisticRegression(object):
  def __init__(self, eta=0.1, n_iter=1000):
    self.eta=eta
    self.n_iter=n_iter
  def fit(self, X, y):
    m,n=X.shape
    ones=tf.ones(shape=[m,1])
    X= tf.concat([ones, X], axis=1)

    self.theta = tf.Variable(tf.random.normal(shape=[n+1, 1]))
    for i in range(self.n_iter):
      gradients = 1 / m * (tf.transpose(X) @ (tf.sigmoid (X @ self.theta)- y))
      self.theta.assign(self.theta - self.eta * gradients)
    return self
  def predict(self,X):
    m,n=X.shape
    ones=tf.ones(shape=[m,1])
    X = tf.concat([ones, X], axis=1)
    return tf.sigmoid(X @ self.theta) >=0.5


In [0]:
import tensorflow.keras as keras

In [0]:
from tensorflow.keras.datasets import mnist

In [0]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [0]:
X_train.shape

(60000, 28, 28)

In [0]:
X_train = tf.constant(X_train.reshape(60000, 784), dtype=tf.dtypes.float32)
X_test = tf.constant(X_test.reshape(10000,784), dtype=tf.dtypes.float32)

In [0]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [0]:
y_train = tf.constant(y_train.reshape(-1, 1)==0, dtype=tf.dtypes.float32)

In [0]:
y_train.shape

TensorShape([60000, 1])

In [0]:
y_train

<tf.Tensor: shape=(60000, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [0]:
log_reg = LogisticRegression()

In [0]:
log_reg.fit(X_train, y_train)

In [0]:
log_reg.theta[:5]

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 0.0425184 ],
       [ 0.28288358],
       [-0.6047016 ],
       [-0.27128848],
       [ 1.8432665 ]], dtype=float32)>

In [0]:
log_reg.predict(X_train[:5])

<tf.Tensor: shape=(5, 1), dtype=bool, numpy=
array([[False],
       [ True],
       [False],
       [False],
       [False]])>

In [0]:
log_reg.predict(X_test[:5])

<tf.Tensor: shape=(5, 1), dtype=bool, numpy=
array([[False],
       [False],
       [False],
       [ True],
       [False]])>

In [0]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [0]:
y_test = tf.constant(y_test.reshape(-1, 1)==0, dtype=tf.dtypes.float32)

In [0]:
y_test[:5]

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [1.],
       [0.]], dtype=float32)>