<a href="https://colab.research.google.com/github/ArchanGhosh/Regression-Practice-Examples/blob/master/Softmax_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf
import numpy as np

In [0]:
class SoftmaxRegression(object):
  def __init__(self, eta=0.1, n_iter=1000):
    self.eta=eta
    self.n_iter=n_iter

  def fit(self, X, y):
    m,n=X.shape
    epsilon= 1e-7
    ones=tf.ones(shape=[m,1])
    X= tf.concat([ones, X], axis=1)

    #y_one_hot=tf.one_hot(y, (len(y)))

    
    
    self.theta = tf.Variable(tf.random.normal(shape=[n_inputs+1, n_outputs]))
    
    for i in range(self.n_iter):
      logits= X @ self.theta
      p_hat=tf.nn.softmax(logits)
      gradients = 1 / m * (tf.transpose (X) @ (p_hat - y))
      self.theta.assign(self.theta - self.eta * gradients)
    return self

  def predict(self,X):
    m,n=X.shape
    ones=tf.ones(shape=[m,1])
    X = tf.concat([ones, X], axis=1)
    logits= X @ self.theta
    p_hat=tf.nn.softmax(logits)
    y_predict=np.argmax(p_hat, axis=1)
    return y_predict
  


In [0]:
import tensorflow.keras as keras

In [0]:
from tensorflow.keras.datasets import mnist

In [0]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [0]:
X_train.shape

(60000, 28, 28)

In [0]:
X_train = tf.constant(X_train.reshape(60000, 784), dtype=tf.dtypes.float32)
X_test = tf.constant(X_test.reshape(10000,784), dtype=tf.dtypes.float32)

In [0]:
y_train


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [0]:
y_train.shape

(60000,)

In [0]:
y_train.shape

(60000,)

In [0]:
y_test.shape

(10000,)

In [0]:
n_inputs = X_train.shape[1]
n_outputs = len(np.unique(y_train))
n_outputs

10

In [0]:
y_one_hot=tf.one_hot(y_train,(n_outputs))

In [0]:
y_one_hot

<tf.Tensor: shape=(60000, 10), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)>

In [0]:
softmax=SoftmaxRegression()

In [0]:
softmax.fit(X_train,y_one_hot)

In [0]:
y_p=softmax.predict(X_test)

In [0]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [0]:
accuracy_score = np.mean(y_p == y_test)
accuracy_score

0.9158